const reviewers=["Tanny","Noah","Hannah"];
const rubric=[
  ["Technical rubric alignment","Score adjustments follow the technical rubric."],
  ["Calibration of technical edits","Technical edits are made only when genuinely needed."],
  ["Style rubric alignment","Style score adjustments follow the style rubric."],
  ["Calibration of style edits","Style edits address clarity or elegance, not preference."],
  ["Focus, concision, and tailoring","Feedback stays specific, focused, and student-appropriate."],
  ["Actionability of grader comments","Comments explain how the grader can improve next time."],
  ["Tone toward graders","Feedback is constructive and mentoring."],
  ["Preservation of grader voice","Sound individual style and voice are retained."],
  ["Plagiarism vigilance","Missed plagiarism concerns are caught and explained."],
  ["Comments to Admin","Warranted cases receive a clear Admin comment."]
];
let submissions=[],view="audit",subjectType="releaser",subject="",sampleRate=10,currentId=null;
let reviewer=localStorage.getItem("aops-demo-reviewer")||"Tanny";
let saved=JSON.parse(localStorage.getItem("aops-demo-ratings")||"{}");
const seeded={"demo-001":["Noah"],"demo-003":["Hannah"],"demo-005":["Noah","Hannah"],"demo-008":["Tanny"]};
const app=document.querySelector("#app"),reviewerSelect=document.querySelector("#reviewer");
reviewerSelect.value=reviewer;

function hash(text){let value=2166136261;for(const char of text){value^=char.charCodeAt(0);value=Math.imul(value,16777619)}return value>>>0}
function people(){return [...new Set(submissions.map(row=>row[subjectType]))].sort()}
function subjectRows(){return submissions.filter(row=>row[subjectType]===subject)}
function sample(){const rows=subjectRows();const count=Math.max(1,Math.ceil(rows.length*sampleRate/100));return [...rows].sort((a,b)=>hash(`${subjectType}|${subject}|2026-07-01|${a.id}`)-hash(`${subjectType}|${subject}|2026-07-01|${b.id}`)).slice(0,count)}
function record(id,name=reviewer){return saved[name]?.[id]}
function isDone(id,name){return Boolean(record(id,name))||Boolean(seeded[id]?.includes(name))}
function statusHtml(id){const own=isDone(id,reviewer);const others=reviewers.filter(name=>name!==reviewer&&isDone(id,name)).length;return `<div class="statuses"><span class="status ${own?"done":""}">${own?"You: done":"You: not started"}</span><span class="status">Others: ${others}/2 done</span></div>`}
function rowHtml(row){return `<tr><td><button class="problem-link" data-open="${row.id}">${row.problem}</button></td><td>${row.grader}</td><td>${new Date(row.date).toLocaleDateString()}</td><td class="number score">${row.graderTech}</td><td>${statusHtml(row.id)}</td></tr>`}
function table(rows){return `<div class="table-wrap"><table><thead><tr><th style="width:32%">Problem</th><th style="width:16%">Grader</th><th style="width:15%">Date</th><th class="number" style="width:8%">Tech</th><th style="width:29%">Status</th></tr></thead><tbody>${rows.map(rowHtml).join("")}</tbody></table></div>`}
function note(){return `<div class="demo-note"><strong>Demonstration only.</strong> All ten submissions, people, comments, and scores are fabricated. Demo saves stay in this browser.</div>`}
function auditView(){const rows=subjectRows(),batch=sample(),done=batch.filter(row=>isDone(row.id,reviewer)).length;app.innerHTML=`${note()}<h1>Audit mode</h1><section class="controls"><label>Review<select id="subject-type"><option value="releaser" ${subjectType==="releaser"?"selected":""}>Releaser</option><option value="grader" ${subjectType==="grader"?"selected":""}>Grader</option></select></label><label>${subjectType==="grader"?"Grader":"Releaser"}<select id="subject">${people().map(name=>`<option ${name===subject?"selected":""}>${name}</option>`).join("")}</select></label><div class="sample"><label>Shared sample<input id="rate" type="number" min="1" max="100" value="${sampleRate}"><span>%</span></label><button class="button primary" id="start">Start batch</button></div></section><section class="panel"><header><div><h2>Shared batch</h2><p>Same frozen IDs for Tanny, Noah, and Hannah; no peer scores shown.</p></div><strong>${sampleRate}% sample</strong></header><div class="summary"><span><strong>${batch.length}</strong>sampled from ${rows.length}</span><span><strong>${done}</strong>completed by you</span><span><strong>Open</strong>for the group</span><span><strong>Jul 1</strong>since previous audit</span></div>${table(batch)}</section><section class="panel"><header><h2>All work</h2><span>${rows.length} submissions</span></header>${table(rows)}</section>`;bindCommon();document.querySelector("#subject-type").onchange=e=>{subjectType=e.target.value;subject=people()[0];render()};document.querySelector("#subject").onchange=e=>{subject=e.target.value;render()};document.querySelector("#start").onclick=()=>{sampleRate=Math.min(100,Math.max(1,Number(document.querySelector("#rate").value)||10));toast("Shared sample frozen");render()}}
function submissionsView(){app.innerHTML=`${note()}<h1>Submissions</h1><section class="panel"><header><h2>Fabricated submission table</h2><span>10 records</span></header>${table(submissions)}</section>`;bindCommon()}
function statsView(){const changed=submissions.filter(row=>row.graderTech!==row.releaseTech||row.graderStyle!==row.releaseStyle).length;app.innerHTML=`${note()}<h1>Stats</h1><div class="stat-grid"><div class="stat-card"><small>Submissions</small><strong>10</strong></div><div class="stat-card"><small>Graders</small><strong>3</strong></div><div class="stat-card"><small>Releasers</small><strong>2</strong></div><div class="stat-card"><small>Scores changed</small><strong>${changed}</strong></div></div>`}
function detailView(){const row=submissions.find(item=>item.id===currentId);const values=record(row.id)?.ratings||{};app.innerHTML=`<button class="back" id="back">← Audit queue</button><section class="detail-card"><div class="detail-head"><h1>${row.problem}</h1><code>${row.id}</code></div><div class="detail-body"><div class="comparison"><div class="text-block"><h3>Student work</h3><p>${row.student}</p><h3>Grader evaluation · ${row.grader}</h3><p><strong>Technical ${row.graderTech} · Style ${row.graderStyle}</strong></p><p>${row.graderFeedback}</p></div><div class="text-block"><h3>Released evaluation · ${row.releaser}</h3><p><strong>Technical ${row.releaseTech} · Style ${row.releaseStyle}</strong></p><p>${row.releasedFeedback}</p><div class="releaser-note"><strong>Releaser → grader/admin</strong><br>${row.releaserComment}</div></div></div><div class="rubric">${rubric.map((item,index)=>`<div class="rubric-row"><div><strong>${item[0]}</strong><small>${item[1]}</small></div><div class="ratings" data-category="${index}">${[[1,"Developing"],[2,"Approaching"],[3,"Proficient"],[0,"N/A"]].map(([value,label])=>`<button class="${values[index]===value?"selected":""}" data-value="${value}"><b>${value||"—"}</b>${label}</button>`).join("")}</div></div>`).join("")}</div><div class="save-row"><button class="button primary" id="save">Save audit</button></div></div></section>`;document.querySelector("#back").onclick=()=>{currentId=null;render()};document.querySelectorAll(".ratings button").forEach(button=>button.onclick=()=>{button.parentElement.querySelectorAll("button").forEach(item=>item.classList.remove("selected"));button.classList.add("selected")});document.querySelector("#save").onclick=()=>{const ratings={};document.querySelectorAll(".ratings").forEach(group=>{const selected=group.querySelector(".selected");if(selected)ratings[group.dataset.category]=Number(selected.dataset.value)});saved[reviewer]??={};saved[reviewer][row.id]={ratings,updatedAt:new Date().toISOString()};localStorage.setItem("aops-demo-ratings",JSON.stringify(saved));toast("Audit saved for "+reviewer)}}
function bindCommon(){document.querySelectorAll("[data-open]").forEach(button=>button.onclick=()=>{currentId=button.dataset.open;render()})}
function render(){document.querySelectorAll("nav a").forEach(link=>link.classList.toggle("active",link.dataset.view===view));if(currentId)return detailView();if(view==="audit")return auditView();if(view==="stats")return statsView();submissionsView()}
function toast(text){const element=document.querySelector("#toast");element.textContent=text;element.classList.add("show");setTimeout(()=>element.classList.remove("show"),1600)}
document.querySelectorAll("[data-view]").forEach(link=>link.onclick=event=>{event.preventDefault();view=link.dataset.view;currentId=null;history.replaceState(null,"",`#${view}`);render()});reviewerSelect.onchange=()=>{reviewer=reviewerSelect.value;localStorage.setItem("aops-demo-reviewer",reviewer);render()};
fetch("fake-submissions.json").then(response=>response.json()).then(data=>{submissions=data;subject=people()[0];view=location.hash.slice(1)||"audit";render()}).catch(()=>app.innerHTML='<div class="demo-note">The fabricated demo data could not be loaded.</div>');
